<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
  version="1.0"	
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:param name="ReportName" select="'Report'" />
  <xsl:variable name="smallcase" select="'abcdefghijklmnopqrstuvwxyz'" />
  <xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />



  <xsl:template match="/">
	<html>
    <head>
	<title><xsl:value-of select="$ReportName" /></title>
      <style>
        h1 {font-size: 18px; font-family: Arial;}
        * {font-family: Arial;}
        p, td,th {font-size: 12px; }
      </style>
    </head>
    
    <h1>
      <xsl:value-of select="$ReportName" /> (<xsl:value-of select="count(Rows/Row)" />)
    </h1>
    
	  <table width="100%" bgcolor="#cccccc" border="0" cellspacing="1" cellpadding="3">
    
    <tr>
      <xsl:for-each select="Rows/Row[1]">
      <xsl:for-each select="@*">
        <th bgcolor="#eeeeee" align="left">
          <xsl:value-of select="translate(name(), $smallcase, $uppercase)" />
        </th>
      </xsl:for-each>
      </xsl:for-each>
    </tr>

    
    <xsl:for-each select="Rows/Row">
		<tr>
      <xsl:for-each select="@*">
        <td  bgcolor="#ffffff">
          <xsl:value-of select="."/>
        </td>
      </xsl:for-each>
    </tr>
		</xsl:for-each>
		</table>

	<p>Generated by <a href="http://www.zynk.com">Zynk</a></p>
	
	</html>
	</xsl:template>
	
</xsl:stylesheet>